### ISSUE TITLE
拉取代码执行完会报错

### ISSUE THREAD

**Issue by nihaoniu** [Eric-chy/gin-api#1]
{
"code": 10000000,
"msg": "服务内部错误",
"data": null,
"elapsed": 0.00009228
}

#File:logger.go:27 
#Msg:[错误信息:：runtime error: invalid memory address or nil pointer dereference] 
#Content:{"header":{"Accept":["text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9"],"Accept-Encoding":["gzip, deflate, br"],"Accept-Language":["zh-CN,zh;q=0.9"],"Cache-Control":["max-age=0"],"Connection":["keep-alive"],"Cookie":["grafana_session=719e9283b15169a149300885ffe955fa"],"Sec-Ch-Ua":["\"Chromium\";v=\"106\", \"Google Chrome\";v=\"106\", \"Not;A=Brand\";v=\"99\""],"Sec-Ch-Ua-Mobile":["?0"],"Sec-Ch-Ua-Platform":["\"macOS\""],"Sec-Fetch-Dest":["document"],"Sec-Fetch-Mode":["navigate"],"Sec-Fetch-Site":["none"],"Sec-Fetch-User":["?1"],"Upgrade-Insecure-Requests":["1"],"User-Agent":["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36"]},"ip":"127.0.0.1","method":"GET","proto":"HTTP/1.1","request":"","response":{"code":10000000,"msg":"服务内部错误","data":null,"elapsed":0.000051408},"url":"127.0.0.1:8888/"}
【ERROR】 [2022-10-15 10:43:22] [ip:127.0.0.1] [GID:24] [RID:1665816202215879]

**Comment by Eric-chy** [comment]
redis哪些时候安装
